### ISSUE TITLE
Search by select-groups

### ISSUE THREAD

**Issue by ilyankou** [tobinbradley/quality-of-life-dashboard#3]
Hey Tobin:

Great project! We are adapting it for Hartford health & housing data here at CTData Collaborative.

I wonder what you think about a search functionality that would perform search by keys of groups defined in `selectgroups.json` of quality-of-life-data repo, e.g. search by neighborhoods. I will attempt to implement it, and I wonder if you'd be interested in having it in the main repo.

All best,
Ilya

**Comment by tobinbradley** [comment]
I think this is a great idea! Please do!
