### ISSUE TITLE
Disable Vue components from data repo

### ISSUE THREAD

**Issue by ilyankou** [tobinbradley/quality-of-life-dashboard#4]
Another improvement idea:

How about letting users disable certain Vue components, e.g. Contact Us form, from a config file in data repo? It could be in `site.json` or in a separate .json config file. This way one would barely ever need to modify dashboard code.

**Comment by tobinbradley** [comment]
This mostly happens now, though it's less explicit, just checking to see whether particular variables are set:

* If there's no embed url in site.json, it won't show the embed.
* What's new won't show if that array is empty or not present.
* Select group won't show if that value is null.

It is supposed to only show the contact form if contactForm isn't null in site.json, but apparently that was busted. I just posted a fix.

Thanks for submitting this! The contact form is a tricky bit, as it's probably custom code for anybody that needs to use it, but at least people can shut it off now :).
